### ISSUE TITLE
Tyranids - Flesh Hooks, again...

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#90] opened 2018-08-02 14:57 UTC
**File:** Tyranids.catz

**BattleScribe version:** 2.01.19

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** I am doing a tyranid kill team.
I have equipped a single Genestealer model with flesh hooks.
I also have equipped two warrior models with flesh hooks.
My lictor model has integral flesh hooks.
I am getting the roster error that says 
“Tyranid v1 (kill team list) has three too many selections of Flesh Hooks (maximum 1)”
The only restriction I’m aware of is for Genestealer models only.  Only one Genestealer model may have flesh hooks.  But there is no restriction on flesh hooks for other models that I’m aware of

**Comment by Mad-Spy** [comment] 2018-08-02 16:44
This should be fixed in release 1.0.5. Please check you have this version.

**Comment by FarseerVeraenthis** [comment] 2018-08-02 21:33
Update your data. The current release version of the Tyranid CAT is v4, if you're on v1 (as mentioned in the bug rep), the problem is already fixed.

**Closed by FarseerVeraenthis** 2018-08-02 21:33 UTC
Labels: Area: validation, Type: bug, ✔ Res: deprecated, 💾 Cat: Tyranids
