### ISSUE TITLE
[Anon] Bug report: Grey Knights.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#438] opened 2020-01-13 02:04 UTC
**File:** Grey Knights.catz

**BattleScribe version:** 2.03.17

**Platform:** Android

**Dropbox:** No

**Description:** Select pair of Falchions as melee weapon. Point cost shown is 2 points, but it should be 1 point as per https://www.warhammer-community.com/commandroster/ and as per FAQ (which says you buy the Falchion as a pair, not each).

**Comment by Mad-Spy** [comment] 2020-01-13 08:53
Duplicate of #437

**Closed by Mad-Spy** 2020-01-13 08:53 UTC
Labels: Area: Costs, Type: bug, ✔ Res: invalid, 💾 Cat: Grey Knights
