### ISSUE TITLE
[Anon] Bug report: Adeptus Astartes.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#344] opened 2019-06-19 11:24 UTC
**File:** Adeptus Astartes.catz

**BattleScribe version:** 2.02.03

**Platform:** Android

**Dropbox:** No

**Description:** Doesnt work and doesnt load. 
Just apper "loading" a lot of time.

**Comment by Mad-Spy** [comment] 2019-06-19 15:17
Duplicate of #321

**Closed by Mad-Spy** 2019-06-19 15:17 UTC
