### ISSUE TITLE
[Anon] Bug report: Adeptus Astartes.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#362] opened 2019-07-18 15:53 UTC
**File:** Adeptus Astartes.catz

**BattleScribe version:** 2.02.03

**Platform:** Android

**Dropbox:** No

**Description:** When attempting to make a list.  It times out and claims my phone doesn't have enough RAM.  If I turn on low RAM mode and it still says it ran out of RAM

**Comment by Mad-Spy** [comment] 2019-07-19 21:01
Duplicate of #321. We're waiting on a fix from the developer.

**Closed by Mad-Spy** 2019-07-19 21:01 UTC
Labels: Area: Battlescribe app, Type: bug
