### ISSUE TITLE
[Anon] Bug report: Heretic Astartes.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#423] opened 2019-12-24 05:50 UTC
**File:** Heretic Astartes.catz

**BattleScribe version:** 2.03.17

**Platform:** Android

**Dropbox:** No

**Description:** The Heretic Astartes Aspiring Champion needs weapon options for chain axe, power maul etc. as found in the Kill Team annual 2019.

**Comment by Mad-Spy** [comment] 2020-01-03 10:28
Duplicate of #408

**Closed by Mad-Spy** 2020-01-03 10:28 UTC
