### ISSUE TITLE
[Anon] Bug report: Orks.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#278] opened 2019-05-20 11:27 UTC
**File:** Orks.catz

**BattleScribe version:** 2.02.03

**Platform:** Android

**Dropbox:** No

**Description:** The gitfinda squig for Flash Gitz/Kaptins is listed as "no cost", while it should be 4 points.

**Comment by Mad-Spy** [comment] 2019-05-20 11:29
Duplicate of #268

**Closed by Mad-Spy** 2019-05-20 11:29 UTC
Labels: Area: Costs, Type: bug, ✔ Res: duplicate, 💾 Cat: Orks
