### ISSUE TITLE
[Anon] Bug report: Tyranids.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#73] opened 2018-07-30 14:57 UTC
**File:** Tyranids.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** If you have a lictor with flesh hooks & a genestealer with flesh hooks, it says the list is invalid. The limit of 1 flesh hooks should be for genestealers only, not the whole kill team. Thanks.

**Comment by Mad-Spy** [comment] 2018-07-30 15:13
This is a duplicate of #59 and will be fixed in the next release 😄

**Closed by Mad-Spy** 2018-07-30 15:13 UTC
