### ISSUE TITLE
[Anon] Bug report: Death Guard.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#316] opened 2019-06-02 12:18 UTC
**File:** Death Guard.catz

**BattleScribe version:** 2.03.29

**Platform:** Android

**Dropbox:** No

**Description:** Combi melta wrong cost on blightlords termies still - it is now 3pts and should be 5pts. Version on BS is 02.03.299

**Comment by Mad-Spy** [comment] 2019-06-03 05:16
Duplicate of #310; already fixed but not yet released.

**Closed by Mad-Spy** 2019-06-03 05:16 UTC
Labels: Area: Costs, Type: bug, ✔ Res: duplicate, 💾 Cat: Death Guard
