### ISSUE TITLE
[Anon] Bug report: Adeptus Astartes.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#370] opened 2019-08-05 17:41 UTC
**File:** Adeptus Astartes.catz

**BattleScribe version:** 2.02.03

**Platform:** Android

**Dropbox:** No

**Description:** After I've set my points limit in the details section, the loading roster box appears but the roster never loads.

**Comment by Mad-Spy** [comment] 2019-08-05 22:27
Duplicate of #321

**Closed by Mad-Spy** 2019-08-05 22:27 UTC
