### ISSUE TITLE
[Anon] Bug report: Adeptus Astartes.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#367] opened 2019-07-31 23:37 UTC
**File:** Adeptus Astartes.catz

**BattleScribe version:** 2.02.04

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Can’t make a kill team lose for Adeptus astartes it will just crash every time

**Comment by Mad-Spy** [comment] 2019-07-31 23:51
Duplicate of #321.

**Closed by Mad-Spy** 2019-07-31 23:51 UTC
