### ISSUE TITLE
[Anon] Bug report: Astra Militarum.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#202] opened 2018-11-08 14:06 UTC
**File:** Astra Militarum.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** The tactical planner abilitie of the company commander should cost 15pts And not 20pts

**Comment by Mad-Spy** [comment] 2018-11-08 14:51
Duplicate of #199

**Closed by Mad-Spy** 2018-11-08 14:51 UTC
Labels: Area: Costs, Type: bug, ✔ Res: duplicate, 💾 Cat: All Catalogues
