### ISSUE TITLE
Tyranids: Crushing Claws missing statline

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#341] opened 2019-06-17 12:51 UTC
**File:** Tyranids.catz

**BattleScribe version:** 2.02.04

**Platform:** Windows

**Dropbox:** No

**Description:** In the tyranid guard, in Scything talons options, "Crushing claws" its blank, no stats are shown

**Comment by Mad-Spy** [comment] 2019-06-17 12:55
Duplicate of #340

**Closed by Mad-Spy** 2019-06-17 12:55 UTC
Labels: Area: text/rule/profile, Type: bug, ✔ Res: duplicate, 💾 Cat: Tyranids
