### ISSUE TITLE
[Anon] Bug report: Tyranids.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#74] opened 2018-07-30 18:17 UTC
**File:** Tyranids.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** While building a Tyranid matched play kill team, I noticed an error notice saying only 1 flesh hook was allowed in my kill team. The limit should only apply to genestealers. I should be able to have a flesh hook on a genestealer and a flesh hook on a warrior and a flesh hook on a lictor at the same time.

**Comment by FarseerVeraenthis** [comment] 2018-07-30 19:33
this is a duplicate of #59 and should be fixed with the next release :smile:

**Closed by FarseerVeraenthis** 2018-07-30 19:33 UTC
