### ISSUE TITLE
[Anon] Bug report: Orks.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#35] opened 2018-07-28 22:12 UTC
**File:** Orks.catz

**BattleScribe version:** 2.01.15

**Platform:** Windows

**Dropbox:** No

**Description:** Ork Boyz have the option of Slugga/Choppa or Shoota, this is not reflected with the the Killteam maker.

**Comment by GenWilhelm** [comment] 2018-07-28 22:22
Duplicate of #28.

**Closed by GenWilhelm** 2018-07-28 22:22 UTC
