### ISSUE TITLE
[Anon] Bug report: Adeptus Astartes.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#259] opened 2019-05-19 14:40 UTC
**File:** Adeptus Astartes.catz

**BattleScribe version:** 2.02.04

**Platform:** Windows

**Dropbox:** Yes

**Description:** Vanguard Sergeants also don't have the correct wargear available

**Comment by Mad-Spy** [comment] 2019-05-19 15:13
Please elaborate as to what the actual problem is. Vague reports are very unhelpful.

**Comment by Mad-Spy** [comment] 2019-05-19 15:31
Duplicate of #252

**Closed by Mad-Spy** 2019-05-19 15:31 UTC
Labels: Area: selections, Type: bug, ✔ Res: duplicate, 💾 Cat: Adeptus Astartes
