### ISSUE TITLE
[Anon] Bug report: Adeptus Astartes.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#342] opened 2019-06-18 16:30 UTC
**File:** Adeptus Astartes.catz

**BattleScribe version:** 2.02.04

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** App crashes and turns off when trying to create a space marine kill team.
Roster never loads

**Comment by Mad-Spy** [comment] 2019-06-19 07:43
Duplicate of #321.

**Closed by Mad-Spy** 2019-06-19 07:43 UTC
Labels: Area: Battlescribe app, Type: bug, ✔ Res: duplicate
