### ISSUE TITLE
[Anon] Bug report: 2021 - Grey Knight.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#662] opened 2021-09-05 16:13 UTC
**File:** 2021 - Grey Knight.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Stormbolter too much Damage.
This is for all individual Minis.

**Comment by Mad-Spy** [comment] 2021-09-05 18:10
Duplicate of #658

**Closed by Mad-Spy** 2021-09-05 18:10 UTC
