### ISSUE TITLE
[Anon] Bug report: Adeptus Astartes.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#339] opened 2019-06-16 23:54 UTC
**File:** Adeptus Astartes.catz

**BattleScribe version:** 2.02.04

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** When I go to adeptus astartes for a kill team, I can’t get the chapter tactics to show up
So I can choose blood angels

**Comment by Mad-Spy** [comment] 2019-06-17 06:41
Duplicate of #338. Faction selection has moved to models.

**Closed by Mad-Spy** 2019-06-17 06:41 UTC
