### ISSUE TITLE
[Anon] Bug report: Warhammer 40,000 Kill Team.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#425] opened 2019-12-27 05:26 UTC
**File:** Warhammer 40,000 Kill Team.gstz

**BattleScribe version:** 2.03.17

**Platform:** Android

**Dropbox:** No

**Description:** Missing model upgrade - for Heretic Astartes - Aspiring Champion does not have Power Axe as an available option.  This weapon upgrade was printed in the Elites rule book expansion.

**Comment by Mad-Spy** [comment] 2020-01-03 10:28
Duplicate of #408

**Closed by Mad-Spy** 2020-01-03 10:28 UTC
