### ISSUE TITLE
[Anon] Bug report: 2021 - Commorrite.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#665] opened 2021-09-05 21:11 UTC
**File:** 2021 - Commorrite.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** For the Commorite’s equipment, the asterisk has a different meaning than it does for most other teams. With the Commorite team, asterisks do not indicate unique equipment across the team, but that each individual model can only take one piece of equipment with an asterisk. The exact wording in the book is “Each operative … cannot be equipped with more than one item marked with a *.” So for the special ammunition types for kabalites and combat drugs for Wyches, multiple operatives can take the same type of drug or ammo, but each operative can only take one type of drug or ammo. Currently BattleScribe has it as each drug and ammo is unique across the kill team, and this is incorrect.

**Comment by Mad-Spy** [comment] 2021-09-05 21:37
Duplicate of #664

**Closed by Mad-Spy** 2021-09-05 21:37 UTC
