### ISSUE TITLE
[Anon] Bug report: T'au Empire.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#499] opened 2020-06-14 12:56 UTC
**File:** T'au Empire.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Kroot leaders count against total specialist limit
Repro:
Select Matched Play configuration
Select Kroot Carnivore as leader
Select Leader specialism
Select any 3 specialists
Battlescribe will detect following error with the list:
"List has 1 too many selections from Specialist (maximum 3)"

**Comment by Mad-Spy** [comment] 2020-06-14 14:36
Duplicate of #498

**Closed by Mad-Spy** 2020-06-14 14:36 UTC
