### ISSUE TITLE
[Anon] Bug report: Adeptus Astartes.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#360] opened 2019-07-13 14:56 UTC
**File:** Adeptus Astartes.catz

**BattleScribe version:** 2.02.03

**Platform:** Android

**Dropbox:** No

**Description:** Battlescribe crashes whenever I try to create an Adeptus Astartes kill team or whenever I try to open an imported Adeptus Astartes roster that's been created on another computer. The error tells me that I don't have enough RAM but crashes anyways even when I switch to low RAM mode. This has been an issue since the Elites expansion was added. I am using an LG K20V and am on Android 7.0.

**Comment by Mad-Spy** [comment] 2019-07-13 19:35
Duplicate of #321

**Closed by Mad-Spy** 2019-07-13 19:35 UTC
