### ISSUE TITLE
[Anon] Bug report: 2021 - Grey Knight.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#663] opened 2021-09-05 18:13 UTC
**File:** 2021 - Grey Knight.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** - Storm bolters for grey knights are currently 4/5 damage, but they are 3/4 for damage

**Comment by Mad-Spy** [comment] 2021-09-05 18:30
Duplicate of #658

**Closed by Mad-Spy** 2021-09-05 18:30 UTC
