### ISSUE TITLE
Adeptus Mechanicus: Data-tether/Omnispex Missing?

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#102] opened 2018-08-06 09:25 UTC
**File:** Adeptus Mechanicus.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** Adeptus Mechanicus v6 I Can't choose Omnispex or Enchant Data trecher for Skitarii Vanguard or skitarii Ranger. It's was working fine in previous version.

**Comment by ohenrik** [comment] 2018-08-06 09:34
Revision 7 is now out and it seems to be working fine there (aka. Im not able to reproduce this). Are you sure you are trying to add Omnispex or Enhanced Data-tether to regular Skitarii Rangers og Skitari Vanguard (not the gunner or Alphas)? In revisions prior to 6 the the gunners and Alphas where by mistake able to select this.

**Comment by amis92** [comment] 2018-08-06 11:01
@ohenrik v7 is not yet available through AppSpot, so it's probably a deprecated issue: http://battlescribedata.appspot.com/#/repo/wh40k-killteam

Retrieved at 2018-08-06 11:00 UTC
![image](https://user-images.githubusercontent.com/2671396/43713075-a1b1da30-9978-11e8-9251-ee35a4534698.png)

**Comment by Mad-Spy** [comment] 2018-08-07 15:06
AdMech v7 is now released in v1.0.6. Should be up on Appspot in the next few hours.

**Closed by Mad-Spy** 2018-08-07 15:06 UTC
Labels: Area: selections, ⛔ Problem: not reproducing, ✔ Res: deprecated, 💾 Cat: Adeptus Mechanicus
