### ISSUE TITLE
[Anon] Bug report: Adeptus Astartes.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#525] opened 2020-11-08 23:16 UTC
**File:** Adeptus Astartes.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Intercessors can choose the auspex, but the annual2019 says they cannot equip themselves with the auspex.

**Comment by Mad-Spy** [comment] 2020-11-09 12:21
Duplicate of #523

**Closed by Mad-Spy** 2020-11-09 12:21 UTC
