### ISSUE TITLE
[Anon] Bug report: Orks.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#414] opened 2019-12-19 10:15 UTC
**File:** Orks.catz

**BattleScribe version:** 2.03.16

**Platform:** Android

**Dropbox:** No

**Description:** Ork weapon cost need to be updated: choppa costs 1pt for Boyz and Kommando, big choppa 3pts for Boyz Nob, klaw 5pts, big choppa for Nobz 2pts, choppa for Nobz 0pts

**Comment by Mad-Spy** [comment] 2019-12-19 10:22
Duplicate of #408

**Closed by Mad-Spy** 2019-12-19 10:22 UTC
