### ISSUE TITLE
[Anon] Bug report: Grey Knights.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#263] opened 2019-05-19 16:55 UTC
**File:** Grey Knights.catz

**BattleScribe version:** 2.02.03

**Platform:** Android

**Dropbox:** No

**Description:** Weapon Options of GKs Terminator Gunner are not correct.
Is: I can choose a weapon out of a list of all melee weapons AND heavy weapons, and still get the stormbolter.
Must be: If i choose a heavy weapon, i loose the stormbolter, but still can take a nemesis melee weapon.

**Comment by Mad-Spy** [comment] 2019-05-19 16:58
Duplicate of #254

**Closed by Mad-Spy** 2019-05-19 16:58 UTC
