### ISSUE TITLE
[Anon] Bug report: Adeptus Astartes.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#381] opened 2019-09-02 10:39 UTC
**File:** Adeptus Astartes.catz

**BattleScribe version:** 2.03.01

**Platform:** Android

**Dropbox:** No

**Description:** Tactical marine gunner can not be chosen heavy specialist.   There are other specialist as comms, sniper etc but heavy is not in the list. I have checked in the manual and tactical marine gunner is the only tactical that could be heavy specialist .

**Comment by Mad-Spy** [comment] 2019-09-02 10:49
Duplicate of #379

**Closed by Mad-Spy** 2019-09-02 10:49 UTC
