### ISSUE TITLE
Lictor flesh-hooks should not count towards maximum flesh-hooks on Genestealer units

### ISSUE THREAD

**Issue by banoffeepy** [BSData/wh40k-killteam#66] opened 2018-07-30 08:48 UTC
When adding Genestealer to a list and selecting flesh hooks as an option. the "too many selections of flesh hooks" error is displayed when a lictor is also in the list (as they come with flesh hooks as standard)

Android mobile
file version: Killteam (2018) 1.2.0

**Comment by FarseerVeraenthis** [comment] 2018-07-30 08:50
This is a duplicate of #59 and will be fixed in the next release :smile:

**Closed by FarseerVeraenthis** 2018-07-30 08:50 UTC

**Comment by banoffeepy** [comment] 2018-07-30 09:04
My bad - thanks for the work
