### ISSUE TITLE
[Anon] Bug report: Death Guard.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#319] opened 2019-06-03 21:08 UTC
**File:** Death Guard.catz

**BattleScribe version:** 1.03.04

**Platform:** Android

**Dropbox:** No

**Description:** Dg combi melta option on blighlords should be 5pts instead of 3pts as it is now in the app

**Comment by Mad-Spy** [comment] 2019-06-03 21:26
Duplicate of #316

**Closed by Mad-Spy** 2019-06-03 21:26 UTC
