### ISSUE TITLE
Hormagaunt uses wrong scything talons

### ISSUE THREAD

**Issue by Windyx11** [BSData/wh40k-killteam#667] opened 2021-09-08 07:17 UTC
**Describe the bug**
Hormagaunt uses tyranid warrior scything talons.

**Expected behavior**
Hormagaunt should have their own version of scything talons. At A4 4+ 3/5 Relentless

**Comment by Mad-Spy** [comment] 2021-09-08 08:16
Duplicate of #661

**Closed by Mad-Spy** 2021-09-08 08:16 UTC
