### ISSUE TITLE
Grey Knights: Terminator weapon options incorrect

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#254] opened 2019-05-19 07:42 UTC
**File:** Grey Knights.catz

**BattleScribe version:** 2.02.02

**Platform:** Android

**Dropbox:** No

**Description:** "A Terminator Gunner may replace their storm bolter with an inceniator, psilencer or psycannon". Now there is no opportunity to do so. I can only change melee weapon.

**Comment by Mad-Spy** [comment] 2019-05-19 15:28
Duplicate of #255

**Closed by Mad-Spy** 2019-05-19 15:28 UTC
Labels: Area: selections, Type: bug, ✔ Res: duplicate, 💾 Cat: Grey Knights
