### ISSUE TITLE
DG and AM havent some specializations 

### ISSUE THREAD

**Issue by simakover** [BSData/wh40k-killteam#248] opened 2019-05-17 14:37 UTC
DG members havent sniper specialization. AM members havent Comms specialization.
offtop: if you add stratagems(like No Force organization in 40k data) i would be happy

**Comment by Mad-Spy** [comment] 2019-05-17 15:17
It's not clear what the issue is here. All of the specialisations available in the data match the current rules (taking into account the errata). If you have a specific model which you believe to be wrong, please let me know.

The Stratagems included in the 40k files are only those which have an effect on list building. There are no such Tactics in Kill Team; all Tactics are only used in game.

**Comment by simakover** [comment] 2019-05-17 17:59
> It's not clear what the issue is here. All of the specialisms available in the data match the current rules (taking into account the errata). If you have specific models which you believe to be wrong, please let me know.
> 
> The Stratagems included in the 40k files are only those which have an effect on list building. There are no such Tactics in Kill Team; all Tactics are only used in game.

sorry, AM working right. But im dont found why death guard cant use sniper specialization, in book its in unit, no changes in errata.

about stratagems, im just about usefull roster, there you can saw units, stats, rules and all stratagems that you can use. in kill team manager( an android app) im can saw stratagems. in 40k rosters you can choose in "No force organisation", [reference] (like SIA for deathwatch or ambushmarkers,brood borthers for GSC) that is just a part of rulebook. if we can choose to [reference] stratagems, roster would be more usefull im think.

**Comment by Mad-Spy** [comment] 2019-05-17 18:13
Unless your rulebook is different to mine, no Death Guard model can take the Sniper Specialism. Can you post a screenshot?

**Comment by Mad-Spy** [comment] 2019-05-20 20:08
Closing as there has been no update on what is incorrect.

**Closed by Mad-Spy** 2019-05-20 20:08 UTC
Labels: Area: selections, Type: bug, ✔ Res: no OP clarification, 💾 Cat: Astra Militarum, 💾 Cat: Death Guard
