### ISSUE TITLE
[Anon] Bug report: Adeptus Astartes.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#364] opened 2019-07-26 02:46 UTC
**File:** Adeptus Astartes.catz

**BattleScribe version:** 2.02.04

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** My iPhone 6 crashes the app every time I try to make that kill team

**Comment by Mad-Spy** [comment] 2019-07-26 08:44
Duplicate of #321

**Closed by Mad-Spy** 2019-07-26 08:44 UTC
