### ISSUE TITLE
[Anon] Bug report: Grey Knights.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#256] opened 2019-05-19 10:14 UTC
**File:** Grey Knights.catz

**BattleScribe version:** 2.02.03

**Platform:** Android

**Dropbox:** No

**Description:** Grey knight teminator gunners weaponry options allow them to swap their melee and gun option both not either one or another like it is now in the app.

**Comment by Mad-Spy** [comment] 2019-05-19 15:28
Duplicate of #254

**Closed by Mad-Spy** 2019-05-19 15:28 UTC
Labels: Area: selections, Type: bug, ✔ Res: duplicate, 💾 Cat: Grey Knights
