### ISSUE TITLE
[Anon] Bug report: Warhammer 40,000 Kill Team.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#443] opened 2020-01-20 02:03 UTC
**File:** Warhammer 40,000 Kill Team.gstz

**BattleScribe version:** 2.03.11

**Platform:** Windows

**Dropbox:** No

**Description:** Adepta Sororita does not have the specialist retainers from blackstone fortress models (godfret and pious vorne)

**Comment by Mad-Spy** [comment] 2020-01-20 11:23
Duplicate of #426

**Closed by Mad-Spy** 2020-01-20 11:23 UTC
